setwd("C:/Users/mtesluk/Desktop/studia/Apu/Lab2")
install.packages("data.tree")
install.packages("formattable")
install.packages("DiagrammeR")
install.packages("C:/Users/mtesluk/Desktop/studia/Apu/Lab2/ahp_0.2.12.tar.gz",repos=NULL,type = "source")

library(ahp)
library(data.tree)
library(formattable)
library(DiagrammeR)

ahpFile <- system.file("extdata", "dane.ahp", package="ahp")
daneAhp <- Load(ahpFile)
Calculate(daneAhp)
Analyze(daneAhp)
AnalyzeTable(daneAhp)
PrioritiesFromPairwiseMatrixMeanNormalization(daneAhp)
